#!/usr/bin/python

import urllib2, sys, json

URL = "http://hastebin.com"

if sys.stdin.isatty():
    with open(sys.argv[1], 'r') as filecontents:
        data = "".join(filecontents.readlines()).strip()
else:
    data = "".join(sys.stdin.readlines()).strip()
    
req = urllib2.Request(URL + "/documents", data)
response = urllib2.urlopen(req)
responsedata = response.read()

sys.stdout.write("%s/%s\n" % (URL, json.loads(responsedata)['key']))