#!/usr/bin/python

# @title Hastebin Python CLI Client
# ------------------------------------------------------------------------------------------
# @author Myles McNamara
# @date 12/18/2012
# @version 1.0
# @source http://github.com/tripflex
# ------------------------------------------------------------------------------------------
# @usage haste ~/thefile
# ------------------------------------------------------------------------------------------
# @copyright Copyright (C) 2012  Myles McNamara
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------------------

import urllib2
import sys

URL = "http://hastebin.com"

if sys.stdin.isatty():
    filecontents = open(sys.argv[1], 'r')
    try:
        data = "".join(filecontents.readlines()).strip()
    finally:
        filecontents.close()
else:
    data = "".join(sys.stdin.readlines()).strip()

req = urllib2.Request(URL + "/documents", data)
response = urllib2.urlopen(req)
responsedata = response.read()
responseeval = eval(responsedata)
sys.stdout.write("%s/%s\n" % (URL, responseeval['key']))